/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaleIndexRouteImport } from './routes/sale/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as SaleOrdersRouteImport } from './routes/sale/orders'
import { Route as InventoryPickingsRouteImport } from './routes/inventory/pickings'
import { Route as CrmPipelineRouteImport } from './routes/crm/pipeline'
import { Route as CrmLeadsRouteImport } from './routes/crm/leads'
import { Route as SaleOrderIdRouteImport } from './routes/sale/order.$id'
import { Route as InventoryPickingIdRouteImport } from './routes/inventory/picking.$id'
import { Route as CrmLeadIdRouteImport } from './routes/crm/lead.$id'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleIndexRoute = SaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleOrdersRoute = SaleOrdersRouteImport.update({
  id: '/sale/orders',
  path: '/sale/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryPickingsRoute = InventoryPickingsRouteImport.update({
  id: '/inventory/pickings',
  path: '/inventory/pickings',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleOrderIdRoute = SaleOrderIdRouteImport.update({
  id: '/sale/order/$id',
  path: '/sale/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryPickingIdRoute = InventoryPickingIdRouteImport.update({
  id: '/inventory/picking/$id',
  path: '/inventory/picking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadIdRoute = CrmLeadIdRouteImport.update({
  id: '/crm/lead/$id',
  path: '/crm/lead/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/web': typeof WebRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/inventory/pickings': typeof InventoryPickingsRoute
  '/sale/orders': typeof SaleOrdersRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/crm/lead/$id': typeof CrmLeadIdRoute
  '/inventory/picking/$id': typeof InventoryPickingIdRoute
  '/sale/order/$id': typeof SaleOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/web': typeof WebRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/inventory/pickings': typeof InventoryPickingsRoute
  '/sale/orders': typeof SaleOrdersRoute
  '/crm': typeof CrmIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/sale': typeof SaleIndexRoute
  '/crm/lead/$id': typeof CrmLeadIdRoute
  '/inventory/picking/$id': typeof InventoryPickingIdRoute
  '/sale/order/$id': typeof SaleOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/settings': typeof SettingsRoute
  '/web': typeof WebRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/inventory/pickings': typeof InventoryPickingsRoute
  '/sale/orders': typeof SaleOrdersRoute
  '/crm/': typeof CrmIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/crm/lead/$id': typeof CrmLeadIdRoute
  '/inventory/picking/$id': typeof InventoryPickingIdRoute
  '/sale/order/$id': typeof SaleOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/settings'
    | '/web'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/inventory/pickings'
    | '/sale/orders'
    | '/crm/'
    | '/inventory/'
    | '/sale/'
    | '/crm/lead/$id'
    | '/inventory/picking/$id'
    | '/sale/order/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/settings'
    | '/web'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/inventory/pickings'
    | '/sale/orders'
    | '/crm'
    | '/inventory'
    | '/sale'
    | '/crm/lead/$id'
    | '/inventory/picking/$id'
    | '/sale/order/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/settings'
    | '/web'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/inventory/pickings'
    | '/sale/orders'
    | '/crm/'
    | '/inventory/'
    | '/sale/'
    | '/crm/lead/$id'
    | '/inventory/picking/$id'
    | '/sale/order/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  SettingsRoute: typeof SettingsRoute
  WebRoute: typeof WebRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  InventoryPickingsRoute: typeof InventoryPickingsRoute
  SaleOrdersRoute: typeof SaleOrdersRoute
  CrmIndexRoute: typeof CrmIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  SaleIndexRoute: typeof SaleIndexRoute
  CrmLeadIdRoute: typeof CrmLeadIdRoute
  InventoryPickingIdRoute: typeof InventoryPickingIdRoute
  SaleOrderIdRoute: typeof SaleOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/': {
      id: '/sale/'
      path: '/sale'
      fullPath: '/sale/'
      preLoaderRoute: typeof SaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/orders': {
      id: '/sale/orders'
      path: '/sale/orders'
      fullPath: '/sale/orders'
      preLoaderRoute: typeof SaleOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/pickings': {
      id: '/inventory/pickings'
      path: '/inventory/pickings'
      fullPath: '/inventory/pickings'
      preLoaderRoute: typeof InventoryPickingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/order/$id': {
      id: '/sale/order/$id'
      path: '/sale/order/$id'
      fullPath: '/sale/order/$id'
      preLoaderRoute: typeof SaleOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/picking/$id': {
      id: '/inventory/picking/$id'
      path: '/inventory/picking/$id'
      fullPath: '/inventory/picking/$id'
      preLoaderRoute: typeof InventoryPickingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/lead/$id': {
      id: '/crm/lead/$id'
      path: '/crm/lead/$id'
      fullPath: '/crm/lead/$id'
      preLoaderRoute: typeof CrmLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  SettingsRoute: SettingsRoute,
  WebRoute: WebRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  InventoryPickingsRoute: InventoryPickingsRoute,
  SaleOrdersRoute: SaleOrdersRoute,
  CrmIndexRoute: CrmIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  SaleIndexRoute: SaleIndexRoute,
  CrmLeadIdRoute: CrmLeadIdRoute,
  InventoryPickingIdRoute: InventoryPickingIdRoute,
  SaleOrderIdRoute: SaleOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
