/** Odoo xml ids for module menu actions (view_mode / views order). */
export const ODOO_ACTION_XML_ID = {
  crm: {
    leads: 'crm.crm_lead_all_leads',
    pipeline: 'crm.crm_lead_opportunities',
    activities: 'crm.crm_lead_action_my_activities',
    forecast: 'crm.crm_lead_action_forecast',
    stages: 'crm.crm_stage_action',
    lostReasons: 'crm.crm_lost_reason_action',
    opportunityForm: 'crm.action_opportunity_form',
    leadMailCompose: 'crm.action_lead_mail_compose',
    leadMassMail: 'crm.action_lead_mass_mail',
    calendarEventNew: 'crm.act_crm_opportunity_calendar_event_new',
    reportSalesteam: 'crm.action_report_crm_lead_salesteam',
  },
  sale: {
    orders: 'sale.action_orders',
    quotations: 'sale.action_quotations_with_onboarding',
    toInvoice: 'sale.action_orders_to_invoice',
    toUpsell: 'sale.action_orders_upselling',
    reporting: 'sale.action_order_report_all',
    partnerOrders: 'sale.act_res_partner_2_sale_order',
    invoiceSalesteams: 'sale.action_invoice_salesteams',
    ordersSalesteams: 'sale.action_orders_salesteams',
  },
  stock: {
    pickings: 'stock.action_picking_tree_all',
    receipts: 'stock.action_picking_tree_incoming',
    deliveries: 'stock.action_picking_tree_outgoing',
    internal: 'stock.action_picking_tree_internal',
    todo: 'stock.action_picking_tree_ready',
    waiting: 'stock.action_picking_tree_waiting',
    late: 'stock.action_picking_tree_late',
    backorder: 'stock.action_picking_tree_backorder',
    moves: 'stock.stock_move_action',
    orderpoints: 'stock.action_orderpoint',
    overview: 'stock.stock_picking_type_action',
    quants: 'stock.action_view_quants',
    moveLines: 'stock.stock_move_line_action',
    productStock: 'stock.action_product_stock_view',
    warehouse: 'stock.action_warehouse_form',
    locations: 'stock.action_location_form',
    packages: 'stock.action_package_view',
    inventoryAdjustment: 'stock.action_view_inventory_tree',
    productLocationOpen: 'stock.act_product_location_open',
    pickingTypeOperations: 'stock.action_get_picking_type_operations',
    pickingTypeReadyMoves: 'stock.action_get_picking_type_ready_moves',
    inventoryAtDate: 'stock.action_inventory_at_date',
    scrap: 'stock.action_stock_scrap',
  },
  account: {
    moves: 'account.action_move_journal_line',
    invoices: 'account.action_move_out_invoice',
    bills: 'account.action_move_in_invoice',
    dashboard: 'account.open_account_journal_dashboard_kanban',
    journalItems: 'account.action_account_moves_all',
    payments: 'account.action_account_payments',
    creditNotes: 'account.action_move_out_refund_type_non_legacy',
    vendorRefunds: 'account.action_move_in_refund_type',
    chartOfAccounts: 'account.action_account_form',
    taxes: 'account.action_tax_form',
    bankStatements: 'account.action_bank_statement_tree',
    reconciliationModels: 'account.action_account_reconcile_model',
    paymentTerms: 'account.action_payment_term_form',
    fiscalPositions: 'account.action_account_fiscal_position_form',
    allPayments: 'account.action_account_all_payments',
    config: 'account.action_account_config',
    auditTrailReport: 'account.action_account_audit_trail_report',
    sendPaymentReceipt: 'account.account_send_payment_receipt_by_email_action',
    sendPaymentReceiptMulti: 'account.account_send_payment_receipt_by_email_action_multi',
    cashRounding: 'account.action_account_cash_rounding',
    incoterms: 'account.action_account_incoterms',
    analyticAccounts: 'account.action_account_analytic_account_form',
  },
  event: {
    events: 'event.action_event_view',
    registrations: 'event.action_registration',
    registrationDesk: 'event.event_barcode_action_main_view',
    eventConfiguration: 'event.action_event_configuration',
    eventRegistrationReport: 'event.action_event_registration_report',
    registrationFromEvent: 'event.act_event_registration_from_event',
    eventQuestionAction: 'event.event_question_action',
  },
  calendar: {
    events: 'calendar.action_calendar_event',
    alarm: 'calendar.action_calendar_alarm',
    eventType: 'calendar.action_calendar_event_type',
    settings: 'calendar.calendar_settings_action',
  },
  product: {
    products: 'product.product_template_action_all',
    productVariants: 'product.product_normal_action',
    productVariantsSell: 'product.product_normal_action_sell',
    productCombo: 'product.product_combo_action',
    productCategoryForm: 'product.product_category_action_form',
    productAttributes: 'product.attribute_action',
  },
  project: {
    projects: 'project.open_view_project_all',
    tasks: 'project.action_view_all_task',
    myTasks: 'project.action_view_my_task',
    stages: 'project.project_project_stage_action',
    taskStages: 'project.open_task_type_form',
    milestones: 'project.action_view_project_milestone',
    projectAllTasks: 'project.act_project_project_2_project_task_all',
    sendMailProject: 'project.action_send_mail_project_project',
    sendMailTask: 'project.action_send_mail_project_task',
  },
  mrp: {
    productions: 'mrp.mrp_production_action',
    productionForm: 'mrp.action_mrp_production_form',
    configuration: 'mrp.action_mrp_configuration',
    routingTime: 'mrp.action_mrp_routing_time',
    unbuildMoves: 'mrp.action_mrp_unbuild_moves',
    workcenterLoadReport: 'mrp.action_mrp_workcenter_load_report_graph',
    boms: 'mrp.mrp_bom_action',
    workOrders: 'mrp.action_mrp_workorder',
    workCenters: 'mrp.action_mrp_workcenter',
    routings: 'mrp.action_mrp_routing_form',
    unbuilds: 'mrp.action_mrp_unbuild',
  },
  attendance: {
    kiosk: 'hr_attendance.hr_attendance_action_kiosk_mode',
    management: 'hr_attendance.hr_attendance_management_action',
    attendanceAction: 'hr_attendance.hr_attendance_action',
    settings: 'hr_attendance.action_hr_attendance_settings',
  },
  hr: {
    employees: 'hr.open_view_employee_list',
    departments: 'hr.open_view_department_list',
    jobPositions: 'hr.action_hr_job',
    createJobPosition: 'hr.action_create_job_position',
    employeeActivities: 'hr.action_hr_employee_all_activities',
    version: 'hr.action_hr_version',
  },
  expense: {
    my: 'hr_expense.action_hr_expense_my_expenses_all',
    all: 'hr_expense.hr_expense_actions_all',
    departmentFiltered: 'hr_expense.action_hr_expense_department_filtered',
    departmentToApprove: 'hr_expense.action_hr_expense_department_to_approve',
    account: 'hr_expense.action_hr_expense_account',
    configuration: 'hr_expense.action_hr_expense_configuration',
  },
  recruitment: {
    applicants: 'hr_recruitment.action_hr_job_applications',
    stages: 'hr_recruitment.action_hr_recruitment_stage',
    department: 'hr_recruitment.action_hr_department',
    configuration: 'hr_recruitment.action_hr_recruitment_configuration',
    reportFilteredDept: 'hr_recruitment.action_hr_recruitment_report_filtered_department',
    reportFilteredJob: 'hr_recruitment.action_hr_recruitment_report_filtered_job',
    talentPool: 'hr_recruitment.action_hr_talent_pool',
  },
  purchase: {
    orders: 'purchase.purchase_form_action',
    rfqs: 'purchase.purchase_rfq',
    vendors: 'purchase.purchase_vendors',
    products: 'purchase.purchase_products',
    partnerOrders: 'purchase.act_res_partner_2_purchase_order',
    supplierInvoices: 'purchase.act_res_partner_2_supplier_invoices',
    accruedExpenseEntry: 'purchase.action_accrued_expense_entry',
    configuration: 'purchase.action_purchase_configuration',
    history: 'purchase.action_purchase_history',
  },
} as const
